language: python

# specify python versions
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
before_script:
  - pip install pytest pytest-cov
  - pip install coveralls

# install the library
install:
  - pip install -e .

# test command
script: py.test --cov=fs

# run coverage after success
after_success: coveralls

branches:
  only:
    - master
    - /.*/
